
GET http://localhost:8080/users HTTP/1.1

###

GET http://localhost:8080/users/1 HTTP/1.1

###

POST http://localhost:8080/users HTTP/1.1
content-type: application/json

{ "userName": "bateau", "firstName": "Chaloupe", "lastName": "Pédalo" }

###

PUT http://localhost:8080/users HTTP/1.1
content-type: application/json

{ "id": 7, "lastName": "Ponton" }

###

DELETE http://localhost:8080/users/7 HTTP/1.1