
GET http://localhost:8080/ HTTP/1.1

###

GET http://localhost:8080/test-json HTTP/1.1

###

GET http://localhost:8080/test-param/allo

###

POST http://localhost:8080/datas/101 HTTP/1.1
Content-Type: application/x-www-form-urlencoded

field1=value1&field2=value2

// Formulaire HTML minimal pour produire la même requête de type post
// <form action="http://localhost:8080/test-json">
//    <input type="text" name="field1" value="value1">
//    <input type="text" name="field2" value="value2">
// </form>

###

POST http://localhost:8080/test-json HTTP/1.1
content-type: application/json

{ "field1": "value1", "field2": "value2" }

// Requête post pour envoyer la même information, mais au format JSON cette fois-ci
