

GET http://localhost:8080/datas/102 HTTP/1.1
Content-Type: application/x-www-form-urlencoded

###

GET http://localhost:8080/datas HTTP/1.1

###

POST http://localhost:8080/datas HTTP/1.1
Content-Type: application/x-www-form-urlencoded

id=104&userName=Aboubakar&age=30

###

PUT http://localhost:8080/datas HTTP/1.1
id=104&userName=Aboubakar&age=33
###