

GET http://localhost:8080/datas/102 HTTP/1.1

###

GET http://localhost:8080/datas HTTP/1.1

###

POST http://localhost:8080/datas HTTP/1.1
content-type: application/json

{ "id": 104, "userName": "Aboubakar", "age":33 }

###

PUT http://localhost:8080/datas HTTP/1.1
content-type: application/json

{ "id": 104, "userName": "Aboubakar", "age":35 }

###